### ISSUE TITLE
Add the ability to fetch external data files from Girder as test external data

### ISSUE THREAD

**Issue by brianhelba** [DigitalSlideArchive/large_image#11]
We'll need to pull down files from https://data.kitware.com/#collection/568d85f28d777f429eac908a , to provide sample data in the tests.

We need a simple API that will download data to a scratch location, cache it, etc. This is basically all the stuff that CMake ExternalData does, but we need an API to it via the Girder test framework.

**Comment by jbeezley** [comment]
I spent a bit of time looking into what is possible, and I want to propose some ideas before I start with the actual work.

If I understood you correctly, you brought up the idea of doing the download somehow inside a unittest `.setUp` method.  I don't think this is a good idea because it abuses how cmake is designed to work.  You also have to manage the complexity of calling cmake from python, which itself is called from ctest.  My preference would be to perform the download during the `configure` or `build` step with an [`ExternalData`](https://cmake.org/cmake/help/v3.3/module/ExternalData.html) call inside [`add_python_test_case`](https://github.com/girder/girder/blob/master/tests/PythonTests.cmake#L70).

What I would propose to add are some extra arguments to [`add_python_test_case`](https://github.com/girder/girder/blob/master/tests/PythonTests.cmake#L70) that will provide a list of files that are needed.  That function would call [`ExternalData`](https://cmake.org/cmake/help/v3.3/module/ExternalData.html) internally and provide the python test environment (through some environment variable) the location of the test files.

As a provisional API, I'm thinking something like this:
```python
add_python_test_case(
    my_test_with_data
    GIRDER_DATA big_file.txt dir1/image.png dir2/sub/image.png
    GIRDER_ROOT https://data.kitware.com/api/v1 # optional
    GIRDER_USER myuser                          # optional
    GIRDER_PASSWORD mypassword                  # optional
    GIRDER_TOKEN ...                            # some sort of auth token in lieu of user/password (optional)
)
```

This would look for the following files in the source tree under `tests/data/` for core tests or `plugins/<PLUGIN>/plugin_tests/data/` for plugin tests containing the expected hashes of the downloaded data:
```
.
├── big_file.txt.{md5,sha1,...}
├── dir1
│   └── image.png.{md5,sha1,...}
└── dir2
    └── sub
        └── image.png.{md5,sha1,...}
```

These files could be used inside the python unittest as follows:
```python
import os
from .. import base
class MyTestCase(base.TestCase):
    def testWIthData(self):
        with big_file as open(os.path.join(os.environ['DATA_ROOT'], 'big_file.txt')):
            pass
        with image1 as open(os.path.join(os.environ['DATA_ROOT'], 'dir1', 'image.png')):
            pass
```

The ExternalData module is less flexible than I originally thought and Girder doesn't support content-addressed downloads (https://github.com/girder/girder/issues/961), so there are a few complications in making this work.  Here are a couple of options:
* Hack around the problem by more or less reimplementing the ExternalData module
* Write the proposed `ContentAddressedDownload` plugin for Girder
* Use MIDAS instead

The quickest route would obviously be to use MIDAS.  In that case, I think we could go with a cmake API as follows to keep backward compatibility when GIrder eventually supports content-address downloads:
```python
add_python_test_case(
    my_test_with_data
    MIDAS_DATA big_file.txt dir1/image.png dir2/sub/image.png
    MIDAS_ROOT http://midas3.kitware.com/midas # optional
)
```

Because this is girder infrastructure, I'll ping @girder/developers for input.
