### ISSUE TITLE
Add button to mark item as large image.

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/large_image#41]

**Comment by brianhelba** [comment]
I'm thinking this could just be a button added on to each [``.g-file-list-entry``](https://github.com/girder/girder/blob/master/clients/web/src/templates/widgets/fileList.jade) to "mark this as a large image", which will kick off the POST request. Since MIME types are a bit unreliable in Girder at the moment, I'm thinking it should be available for every listed file.

Once the large image exists, the button should change to only be present on the active large image, and allow a DELETE request to be sent (as well as to signify which image is marked).

It would also be nice to have a special signifier for when an image creation task is pending (i.e. ``item.largeImage.expected == true``)/

**Comment by manthey** [comment]
Should there be an option to show this or not (like controlling whether we show thumbnails and the viewer via settings)?

**Comment by brianhelba** [comment]
IMO, no. These should be tiny, non-intrusive icons that directly map to the REST endpoints that the plugin provides.

**Comment by manthey** [comment]
Added in PR #43.
