### ISSUE TITLE
Set cache sizes based on system's available memory

### ISSUE THREAD

**Issue by brianhelba** [DigitalSlideArchive/large_image#51]

**Comment by brianhelba** [comment]
Also verify that caching is working as intended.

**Comment by manthey** [comment]
Currently, we aren't caching very much -- just the initial parsing of each ptif or svs file, and then only for a minute.  We create a cache per class (currently there are two for girder items of the different file types).  Within these restrictions, the cache is working.

At the least, we can create a cache based on memory size.  The individual instances of the classes don't use a huge amount of memory, as they don't include the tiles.  We can cache tiles and thumbnails within the instances, which, in a trial, helps quite a lot when reloading a browser page so that the browser cache is avoided.

Instead of one cache per tile source class, I think we should have (a) a common cache for the tile sources, rather than one cache per source, (b) a common cache for tiles, regardless of source, and (c) a common cache for thumbnails.  In this way, we can use a large percentage of available memory for the cache, whereas with separate caches, we need to keep them much smaller in case multiple sources are in use.  I would also greatly increase the expiration time of the caches.

**Comment by manthey** [comment]
Added in PR #56.
